# Generated by Django 5.2.9 on 2025-12-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='origin',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='service',
            field=models.CharField(default='Standard', max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='shipment',
            name='estimated_delivery',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
