# Generated by Django 5.2.9 on 2025-12-25 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_shipment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('permit_number', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('hire_date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('zone_geographique', models.CharField(max_length=50)),
                ('tarif_base', models.DecimalField(decimal_places=2, max_digits=8)),
                ('distance_km', models.FloatField(help_text='Distance depuis le dépôt principal')),
                ('temps_estime', models.FloatField(help_text='Temps estimé en heures')),
            ],
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('multiplicateur_tarif', models.FloatField(default=1.0)),
                ('temps_livraison_base', models.FloatField(help_text='Temps de livraison de base en heures')),
                ('poids_max', models.FloatField(help_text='Poids maximum autorisé en kg')),
                ('est_disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('marque', models.CharField(max_length=50)),
                ('capacite', models.FloatField(help_text='Capacité en kg')),
                ('consommation', models.FloatField(help_text='Consommation en L/100km')),
                ('etat', models.CharField(choices=[('Disponible', 'Disponible'), ('En service', 'En service'), ('Maintenance', 'Maintenance'), ('Hors service', 'Hors service')], max_length=20)),
                ('date_achat', models.DateField()),
                ('dernier_entretien', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='shipment',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='estimated_delivery',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='origin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='service',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Tarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarif_par_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tarif_fixe', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('tarif_minimum', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.destination')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typeservice')),
            ],
            options={
                'unique_together': {('service', 'destination')},
            },
        ),
    ]
